# Numpy, Pandas and Matplotlib


In [1]:
#Numpy is a library consists array objects and routines for array processing
#It is an array processing package

import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print(a)
print(a.shape) #shape is not a functiom :) it is an 'ndarray' object returns tuple of array dimension
print(a.size) #size object gives size of array
print(type(a))




[[1 2 3]
 [4 5 6]]
(2, 3)
6
<class 'numpy.ndarray'>


In [12]:
#to reshape

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a,"\n",a.shape)
a.shape = (6,1) #imp (rows,columns) rows = horizontal, column = vertical
print(a)

#or reshape function

b = a.reshape(3,2) #==> 3 * 2 = 6 ,6 *1 = 6
print(b)

[[1 2 3]
 [4 5 6]] 
 (2, 3)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]


In [19]:
#to resize

import numpy as np

a = np.array([[1,2,3],[4,5,6]])

b = np.resize(a,(6,5)) #if dimensions exceed the size the element repeat
print(b)

[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]
 [4 5 6 1 2]
 [3 4 5 6 1]
 [2 3 4 5 6]]


In [26]:
#arange function

import numpy as np

a = np.arange(1,51,2,dtype = np.float)
#print(a)

# It can be reshaped
a.shape = (5,5)

print(a)
print("dimensions of array object is " ,a.ndim)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]
 [31. 33. 35. 37. 39.]
 [41. 43. 45. 47. 49.]]
dimensions of array obect is  2


In [8]:
# ndim object to check dimension
import numpy as np 
a = np.arange(24) 
print("dimensions of array object a is " ,a.ndim)

b = a.reshape(2,2,2,3)
#THIS IS IMPORTANT
#In Matrix terms no of elements always equal to product of no of rows and columns
print("reshaped array with dimensions",b.ndim)
print(b)

dimensions of array object a is  1
reshaped array with dimensions 4
[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


In [37]:
#numpy.itemsize: returns length of element in bytes
import numpy as np 

x = np.array([1,2,3,4,5],dtype = np.int64) 
print(x.itemsize)

y = np.array([1,2,3,4,5],dtype = np.int32) 
print(y.itemsize)

#int8 = 1 byte i.e, int64 = 8 bytes

8
4


In [4]:
#numpy.empty => creates an uninitialized array with specified shape and dtype
#format -> numpy.empty([shape],dtype=)
import numpy as np

a = np.empty([3,4], dtype = np.int64)
print(a)

[[37498736        0        0        0]
 [       0        0        0        0]
 [       0        0        0        0]]


In [1]:
#numpy.zeros

import numpy as np

a = np.zeros([5,5],dtype = np.int64)

print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [2]:
#numpy.ones

import numpy as np

o = np.ones([3,4],dtype=np.float)

print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#asarray

import numpy as np 
x = [1,2,3] 
a = np.asarray(x)
b=list(a) # from array to list 
print (a)
print(type(a))
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>
<class 'list'>


In [9]:
#**linspace = similar to arange and it outputs the evenly spaced values between the interval

import numpy as np 
x = np.linspace(10,20,5,dtype = np.int64) 
print (x)

[10 12 15 17 20]


# Arithmetic Operations


In [12]:
#np.sum

import numpy as np

a = np.array([[0,1],[3,5]])
print(np.sum(a))
print(np.sum(a,axis = 0))#for  column 0
print(np.sum(a,axis = 1))

9
[3 6]
[1 8]


# Matrix operations

In [16]:

import numpy as np

a=np.array([[0,1,2],[2,3,4]])
b=np.array([[4,5,6],[1,3,2]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
#print(np.dot(a,b))

[[4 6 8]
 [3 6 6]]
[[-4 -4 -4]
 [ 1  0  2]]
[[ 0  5 12]
 [ 2  9  8]]
[[0.         0.2        0.33333333]
 [2.         1.         2.        ]]


# Statistical Functions

In [17]:
#min and max functions along row and columns
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(np.amin(a,axis=1))#  0 for column 1 for row
print(np.amin(a,axis=0))
print(np.amax(a,axis=1))
print(np.amax(a,axis=0))


[3 3 2]
[2 4 3]
[7 8 9]
[8 7 9]


In [18]:
#numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(np.ptp(a))
print(np.ptp(a,axis=1))
print(np.ptp(a,axis=0))


7
[4 5 7]
[6 3 6]


In [2]:
#mumpy.median == it is a value separating from higher half of a data sample from the lower half

import numpy as np

a = np.array([[30,65,70],[80,95,10],[50,90,60]])

print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a,axis=1))

65.0
[50. 90. 60.]
[65. 80. 60.]


In [3]:
#numpy.mean() function returns the arithmetic mean of elements in the array. 

import numpy as np 

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.6666666666666665
[2.66666667 3.66666667 4.66666667]
[2. 4. 5.]


In [5]:
#numpy.average() function computes the weighted average of elements in an array

#***Remember how to calculate weighted avg == weighted average is calculated by 
#adding the product of the corresponding elements and dividing the sum by the sum of weights

import numpy as np 
a = np.array([1,2,3,4]) 
print(np.average(a))
print(np.mean(a))

wts = np.array([4,3,2,1]) 
print(np.average(a,weights=wts))


2.5
2.5
2.0


In [6]:
#numpy.std == Standard deviation is the square root of the average of squared deviations from mean.
#formula == std = sqrt(mean(abs(x - x.mean())**2))

import numpy as np 
print (np.std([1,2,3,4])) 


1.118033988749895


In [8]:
## IMPORTANT

##numpy.var() == Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2)
##* the standard deviation is the square root of variance.

import numpy
print(numpy.var([1,3,4,6]))

3.25


In [10]:
#broadcasting = broadcasting refers to the ability of NumPy to 
#treat arrays of different shapes during arithmetic operations
 
 
 


# Pandas #

#pandas = Python library providing high-performance, easy-to-use data structures and 
#data analysis tools for the Python programming language

#merging and joining of data.

# Pandas - Series

Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.). The axis labels are collectively called index.


Series( data, index, dtype, copy)

In [2]:
import pandas as pd 
import numpy as np 
data = np.array(['a','b','c','d']) 
s=pd.Series(data)
print( s)
s = pd.Series(data,index=[100,101,102,103]) #these numbers are axis labels
print( s) 

0    a
1    b
2    c
3    d
dtype: object
100    a
101    b
102    c
103    d
dtype: object


In [1]:
#Series from dict
#Note the dtype **
import pandas as pd  
data = {'a':0,'b':1,'c':2}
s = pd.Series(data) 
print( s)

data = {'a':0,'b':1,'c':2,'f':3}
s = pd.Series(data,index=['b','c','d','a','e'])	
print( s)

a    0
b    1
c    2
dtype: int64
b    1.0
c    2.0
d    NaN
a    0.0
e    NaN
dtype: float64


In [7]:
#Accessing data from series

import pandas as pd
s=pd.Series([1,2,3,4],index=['a','b', 'c', 'd'])
print(s[0]) 			#print using position
print(s[:3])
print(s[2:4])
print(s['c'])			#print using label


1
a    1
b    2
c    3
dtype: int64
c    3
d    4
dtype: int64
3


# Pandas - DataFrames

A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.


In [17]:
#dataframe from list

import pandas as pd
data=[1,2,3,4,5]
d1=pd.DataFrame(data)
print(d1)

import pandas as pd 
data = [['Alex',10],['Bob',12],['Clarke',13]] 
df = pd.DataFrame(data,columns=['Name','Age']) 
print (df)

data2 = [['Alex',10],['Bob',12],['Clarke',13]] 
df1 = pd.DataFrame(data2,index=['a','b','c'], columns=['Name','Age']) 
print (df1)


   0
0  1
1  2
2  3
3  4
4  5
     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13
     Name  Age
a    Alex   10
b     Bob   12
c  Clarke   13


In [20]:
#from dict of lists

import pandas as pd
data={'Name': ['John', 'Tom', 'Mary'], 'Age': [23,33,25]}
d1=pd.DataFrame(data,index=['Student1', 'Student2', 'Student3'])
print(d1)

          Name  Age
Student1  John   23
Student2   Tom   33
Student3  Mary   25


In [23]:
#from list of dict


import pandas as pd
data=[{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c':4}]
d1=pd.DataFrame(data)
print(d1)

   a   b    c
0  1   2  NaN
1  5  10  4.0


In [11]:
#from dict of series

import pandas as pd

d = { "one" : pd.Series([1,2,3,4],index=['a','b','c','d']), "two" : pd.Series([1,2,3],index = ['a','g','c'])}
df = pd.DataFrame(d)
print(df)

#column selection

print("column selection\n",d['two'])
print("column selection of DF\n",d['one'])

   one  two
a  1.0  1.0
b  2.0  NaN
c  3.0  3.0
d  4.0  NaN
g  NaN  2.0
column selection
 a    1
g    2
c    3
dtype: int64
column selection of DF
 a    1
b    2
c    3
d    4
dtype: int64


In [13]:
#Column Addition

import pandas as pd 
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])} 
df = pd.DataFrame(d)

# Adding a new column to an existing DataFrame object with column label by passing new series 
print("Adding a new column by passing as Series:") 

df['three']=pd.Series([10,20,30],index=['a','b','c']) 
print(df)
 
print("Adding a new column using the existing columns in DataFrame:") 
df['four']=df['one']+df['three'] 

print (df)

Adding a new column by passing as Series:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
Adding a new column using the existing columns in DataFrame:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN


In [16]:
import pandas as pd 
dn = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd']), 'three' : pd.Series([10,20,30], index=['a','b','c'])} 
dfn = pd.DataFrame(dn) 
print("Our dataframe is:") 
print(dfn)

 # using del function 
print ("Deleting the first column using DEL function:") 
del dfn['one'] 
print(dfn)

# using pop function 
print("Deleting another column using POP function:")
dfn.pop('two') 
print(dfn)

Our dataframe is:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
Deleting the first column using DEL function:
   two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN
Deleting another column using POP function:
   three
a   10.0
b   20.0
c   30.0
d    NaN


In [19]:
#Row Selection

#Rows can be selected by passing row label to a loc function. 
#Program
import pandas as pd 
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])} 
df = pd.DataFrame(d) 
print(df,"\n")
print( df.loc['b'])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4 

one    2.0
two    2.0
Name: b, dtype: float64


In [21]:
#Rows can be selected by passing integer location to an iloc function.
#Program

import pandas as pd 
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])} 
df = pd.DataFrame(d) 
print( df.iloc[2])

#slice rows
print(df[2:4])

one    3.0
two    3.0
Name: c, dtype: float64
   one  two
c  3.0    3
d  NaN    4


In [25]:
#Add new rows to a DataFrame using the append function. 
#Program
import pandas as pd 
df1 = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'],index = ['x','z']) 
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'],index = ['y' , 's']) 
df1 = df1.append(df2) 
print (df)

   a  b
x  1  2
z  3  4
y  5  6
s  7  8


# Matplotlib continued in another ipynb file ; Stay Safe , Stay Corona :)